# Project: aula11_09
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o fila.o
LINKOBJ  = main.o fila.o
LIBS     = -L"D:/Dev-C++/Dev-Cpp/MinGW64/lib" -L"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-C++/Dev-Cpp/MinGW64/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-C++/Dev-Cpp/MinGW64/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = aula11_09.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

fila.o: fila.c
	$(CC) -c fila.c -o fila.o $(CFLAGS)
